name: CI

on:
  pull_request:
  push:
    branches: [ main, temp-yml ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
  
    services: 
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports: 
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install

      - name: Set up MySQL configuration for test
        run: |
          cp config/database.yml.github-actions config/database.yml

      - name: Wait for MySQL to be ready
        run: |
          docker exec mysql mysqladmin --user=root --password=ping --host=127.0.0.1 --port=3306 --silent

      - name: Prepare database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:seed

      - name: Run RSpec tests
        run: bundle exec rspec
      
      # - name: Run database 
      #   env: 
      #     MYSQL_HOST: 127.0.0.1
      #     MYSQL_ROOT_PASSWORD: ''
      #     MYSQL_PASSWORD: ''
      #     MYSQL_USER: root
      #   run: |
      #     bundle install
      #     bundle exec rake db:create
      #     bundle exec rake db:migrate

      # - name: Run RSpec tests
      #   env: 
      #     MYSQL_HOST: 127.0.0.1
      #     MYSQL_ROOT_PASSWORD: ''
      #     MYSQL_PASSWORD: ''
      #     MYSQL_USER: root
      #   run: bundle exec rspec
